Formula evaluation order testing and documentation
3mcloud/farser pull request #7
Opened 2022-08-08 14:17 UTC by thnaeff

Addition testing of formula evaluation order. Operator precedence and evaluation order documented.

A few generic type names aligned (`C` types) and their javadoc updated. This helped me a lot to get into using farser again and figuring out how to construct all object types.

Various javadoc updates.

`equals`/`hashCode` added to lexer token classes.

2022-08-08 14:31 UTC, mfunaro requested changes

2022-08-08 14:31 UTC, mfunaro commented on src/main/java/com/mmm/his/cer/utility/farser/ast/node/type/NodeSupplier.java
> -public interface NodeSupplier<T, R> {
`R` was used to represent the return type. I would prefer that stays the same.

2022-08-08 14:31 UTC, mfunaro commented on src/main/java/com/mmm/his/cer/utility/farser/ast/node/type/NonTerminal.java
> -public abstract class NonTerminal<T> implements BooleanExpression<T> {
When a single generic type is used, I prefer the canonical `T` is used.

2022-08-08 14:31 UTC, mfunaro commented on src/main/java/com/mmm/his/cer/utility/farser/ast/parser/DescentParser.java
> -public class DescentParser<T> {
Same thing here. Use the canonical `T` for a single generic type.

2022-08-08 14:31 UTC, mfunaro commented on src/test/java/com/mmm/his/cer/utility/farser/ast/AstTest.java
> +  public static class StringOperandSupplier implements
It might be better to move this to it's own class, now that it is public and used elsewhere. It will be move obvious for use cases outside this Test.

2022-08-08 14:33 UTC, rowsimms42 approved these changes

2022-08-08 14:41 UTC, thnaeff commented on src/main/java/com/mmm/his/cer/utility/farser/ast/node/type/NodeSupplier.java
> -public interface NodeSupplier<T, R> {
But it is not the return type, it is the type of the context data which the returned `BooleanExpression<C>` has to be able to handle. The node supplier has to return boolean expression nodes with context type C - the same context type used in all the other AST setup.
It took me a while to get up to speed again and match up all generic types, and this helped a lot. I generally like to name generic types which represent the same thing with the same letter across a library like this.

2022-08-08 14:44 UTC, thnaeff commented on src/main/java/com/mmm/his/cer/utility/farser/ast/node/type/NonTerminal.java
> -public abstract class NonTerminal<T> implements BooleanExpression<T> {
Same reasoning as above.
The naming does not matter so much, but in my opinion since you _can_ choose the generic type letter why not choose one that somehow describes your variable/use. And in addition, helps with matching up the types all across the library.

2022-08-08 14:49 UTC, rowsimms42 approved these changes

2022-08-08 14:54 UTC, mfunaro commented on src/main/java/com/mmm/his/cer/utility/farser/ast/node/type/NodeSupplier.java
> -public interface NodeSupplier<T, R> {
It's the generic type that is used in the _return_ type. That is why I like it labeled `R` because it it the generic type used for the return. The javadoc for the type will provide the details needed. As you prefer to the naming one way, I prefer it this way as it give me a clue how it is used within the class, namely that it is used in the return.

2022-08-08 14:55 UTC, mfunaro commented on src/main/java/com/mmm/his/cer/utility/farser/ast/node/type/NonTerminal.java
> -public abstract class NonTerminal<T> implements BooleanExpression<T> {
It is a single letter and does not actually _describe_ anything. The Javadoc will provide the details to describe what the generic type will actually do.

2022-08-08 15:11 UTC, thnaeff commented on src/main/java/com/mmm/his/cer/utility/farser/ast/node/type/NodeSupplier.java
> -public interface NodeSupplier<T, R> {
Just the hint that one `C` in the library is most likely the same type as all the other `C`s in the library does help me a lot to get started at least to set up types. I do use `T`/`R`/`E` more when it really is just "any object/element/enum", and within a class the placement of the type will provide me with the details needed to implement the class.
But as you said, different preferences.

2022-08-08 15:26 UTC, mfunaro approved these changes

2022-08-12 18:42 UTC, thnaeff commented
@mfunaro  and @rowsimms42  any luck yet? I need to reviews from write-access users

2022-08-15 14:08 UTC, mfunaro approved these changes

2022-08-15 14:19 UTC, rowsimms42 approved these changes

2022-08-15 14:19 UTC, rowsimms42 commented on readme.md
> +| logical/binary OR  |  \|             |
should this just be `|` instead of `\|`? not sure if it is a formatting thing or not. edit- never mind... I see when I made that comment without using `` the slash doesn't appear, so it is a formatting thing

2022-09-21 12:26 UTC, merged